import type { NextPage } from "next";
import Head from "next/head";

const Profile: NextPage = () => {
  return (
    <div>
      <Head>
        <title>OctoProfile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" href="/favicon.png" />
      </Head>
      <div>Hi</div>
    </div>
  );
};

export default Profile;
