import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { css } from "@emotion/react";
import { Header } from "@lib/atoms";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>OctoProfile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className="container"
        css={css`
          display: flex;
          flex-direction: column;
        `}
      >
        <Header />
        <Image
          src="/circles.svg"
          width={828}
          height={861}
          alt="circles"
          priority
        />
      </div>
    </div>
  );
};

export default Home;
