import type { NextPage } from "next";
import Head from "next/head";
import { FC } from "react";

import { css } from "@emotion/react";

const Home: NextPage = () => {
  const color = "white";

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        css={css`
          padding: 32px;
          background-color: hotpink;
          font-size: 24px;
          border-radius: 4px;
          &:hover {
            color: ${color};
          }
        `}
      >
        Hello world
      </div>
    </div>
  );
};

export default Home;
