#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# used npm.cmd to fix issue with GitHub Desktop. see: https://github.com/desktop/desktop/issues/12562#issuecomment-1007154382

echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
npm.cmd run check-format ||
(
    echo ' Your styling looks disgusting. 🤢🤮🤢🤮
            Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)

# Check ESLint Standards
npm.cmd run check-lint ||
(
        echo 'ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# Check tsconfig standards
npm.cmd run check-types ||
(
    echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
            Are you seriously trying to write that? Make the changes required above.'
    false;
)

# # If everything passes... Now we can commit
# echo '🤔🤔🤔🤔... Alright.... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

# npm.cmd run build ||
# (
#     echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
#             Next build failed: View the errors above to see why. 
#     '
#     false;
# )

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'